const mongoose = require('mongoose');

const ledgerTransactionSchema = new mongoose.Schema({
  member: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Member',
    required: true,
    index: true,
  },
  type: {
    type: String,
    enum: ['debit', 'credit'],
    required: true,
  },
  category: {
    type: String,
    enum: [
      'maintenance',
      'late_fee',
      'interest',
      'advance',
      'water_charge',
      'parking_charge',
      'special_levy',
      'repair_charge',
      'refund',
      'other',
    ],
    required: true,
  },
  amount: {
    type: Number,
    required: [true, 'Amount is required'],
    min: [0, 'Amount must be positive'],
  },
  description: {
    type: String,
    required: [true, 'Description is required'],
    trim: true,
    maxlength: 500,
  },
  date: {
    type: Date,
    default: Date.now,
    index: true,
  },
  month: {
    type: Number, // 1-12
    required: true,
  },
  year: {
    type: Number,
    required: true,
  },
  balance: {
    type: Number,
    required: true,
  },
  paymentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Payment',
    default: null,
  },
  referenceNumber: {
    type: String,
    trim: true,
  },
  receiptNumber: {
    type: String,
    unique: true,
    sparse: true,
  },
  receiptUrl: String,
  isAutoGenerated: {
    type: Boolean,
    default: false, // true for cron-generated maintenance entries
  },
  status: {
    type: String,
    enum: ['pending', 'paid', 'overdue', 'waived'],
    default: 'pending',
  },
  paidOn: Date,
  dueDate: Date,
  lateFeeApplied: {
    type: Boolean,
    default: false,
  },
  lateFeeAmount: {
    type: Number,
    default: 0,
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  },
  notes: String,
}, {
  timestamps: true,
});

// ─── Indexes ─────────────────────────────────────────────────────────────────
ledgerTransactionSchema.index({ member: 1, date: -1 });
ledgerTransactionSchema.index({ month: 1, year: 1 });
ledgerTransactionSchema.index({ status: 1 });
ledgerTransactionSchema.index({ category: 1 });

// ─── Static: Running balance ──────────────────────────────────────────────────
ledgerTransactionSchema.statics.getRunningBalance = async function (memberId) {
  const result = await this.aggregate([
    { $match: { member: memberId } },
    {
      $group: {
        _id: null,
        totalDebit: { $sum: { $cond: [{ $eq: ['$type', 'debit'] }, '$amount', 0] } },
        totalCredit: { $sum: { $cond: [{ $eq: ['$type', 'credit'] }, '$amount', 0] } },
      },
    },
  ]);
  if (result.length === 0) return 0;
  return result[0].totalDebit - result[0].totalCredit;
};

// ─── Static: Pending dues ─────────────────────────────────────────────────────
ledgerTransactionSchema.statics.getPendingDues = async function (memberId) {
  const result = await this.aggregate([
    { $match: { member: memberId, status: { $in: ['pending', 'overdue'] }, type: 'debit' } },
    { $group: { _id: null, total: { $sum: '$amount' } } },
  ]);
  return result.length > 0 ? result[0].total : 0;
};

// ─── Pre-save: Generate receipt number ────────────────────────────────────────
ledgerTransactionSchema.pre('save', async function (next) {
  if (!this.receiptNumber && this.type === 'credit') {
    const count = await this.constructor.countDocuments();
    this.receiptNumber = `RCP${Date.now()}${count + 1}`;
  }
  next();
});

module.exports = mongoose.model('LedgerTransaction', ledgerTransactionSchema);
