const cron = require('node-cron');
const Member = require('../models/Member');
const LedgerTransaction = require('../models/LedgerTransaction');
const User = require('../models/User');
const { sendPushNotification, sendBroadcastNotification } = require('./notificationService');
const { sendEmail } = require('./emailService');
const logger = require('../utils/logger');

exports.startCronJobs = () => {
  logger.info('⏰ Starting cron jobs...');

  // ─── 1st of every month: Auto-generate maintenance ──────────────────────────
  cron.schedule('0 9 1 * *', async () => {
    logger.info('CRON: Generating monthly maintenance...');
    try {
      const month = new Date().getMonth() + 1;
      const year = new Date().getFullYear();
      const members = await Member.find({ isActive: true }).populate('user');

      for (const member of members) {
        const existing = await LedgerTransaction.findOne({
          member: member._id, month, year, category: 'maintenance', isAutoGenerated: true,
        });
        if (existing) continue;

        const balance = await LedgerTransaction.getRunningBalance(member._id);
        const dueDate = new Date(year, month - 1, member.maintenanceDueDay);

        await LedgerTransaction.create({
          member: member._id,
          type: 'debit',
          category: 'maintenance',
          amount: member.monthlyMaintenance,
          description: `Monthly Maintenance - ${new Date(year, month - 1).toLocaleString('default', { month: 'long', year: 'numeric' })}`,
          date: new Date(year, month - 1, 1),
          month, year,
          balance: balance + member.monthlyMaintenance,
          dueDate, status: 'pending', isAutoGenerated: true,
        });
      }
      logger.info(`CRON: Maintenance generated for ${month}/${year}`);
    } catch (err) {
      logger.error('CRON: Maintenance generation failed:', err);
    }
  }, { timezone: 'Asia/Kolkata' });

  // ─── 3 days before due date: Reminder notification ──────────────────────────
  cron.schedule('0 10 * * *', async () => {
    logger.info('CRON: Checking payment reminders...');
    try {
      const threeDaysLater = new Date();
      threeDaysLater.setDate(threeDaysLater.getDate() + 3);
      const today = new Date();

      // Due in 3 days
      const upcomingDue = await LedgerTransaction.find({
        type: 'debit',
        category: 'maintenance',
        status: 'pending',
        dueDate: {
          $gte: new Date(threeDaysLater.setHours(0, 0, 0, 0)),
          $lte: new Date(threeDaysLater.setHours(23, 59, 59, 999)),
        },
      }).populate({ path: 'member', populate: { path: 'user' } });

      for (const txn of upcomingDue) {
        if (!txn.member?.user) continue;
        await sendPushNotification({
          userId: txn.member.user._id,
          title: '💰 Maintenance Due in 3 Days',
          body: `₹${txn.amount.toLocaleString('en-IN')} due on ${new Date(txn.dueDate).toLocaleDateString('en-IN')}. Pay early to avoid late fees.`,
          data: { type: 'payment_reminder', amount: String(txn.amount) },
        });
      }

      // Overdue: mark and send reminder
      const overdue = await LedgerTransaction.find({
        type: 'debit',
        category: 'maintenance',
        status: 'pending',
        dueDate: { $lt: today },
      }).populate({ path: 'member', populate: { path: 'user' } });

      for (const txn of overdue) {
        txn.status = 'overdue';
        await txn.save();

        if (!txn.member?.user) continue;
        await sendPushNotification({
          userId: txn.member.user._id,
          title: '⚠️ Maintenance Overdue',
          body: `₹${txn.amount.toLocaleString('en-IN')} is overdue. Late fee will be applied. Please pay immediately.`,
          data: { type: 'payment_reminder', overdue: 'true' },
        });

        // Email reminder
        if (txn.member.user.email) {
          await sendEmail({
            to: txn.member.user.email,
            subject: '⚠️ Overdue Maintenance Payment',
            template: 'paymentReminder',
            data: {
              name: txn.member.user.name,
              amount: txn.amount,
              dueDate: new Date(txn.dueDate).toLocaleDateString('en-IN'),
              flat: `${txn.member.wing}-${txn.member.flatNumber}`,
            },
          }).catch(() => {});
        }
      }

      logger.info(`CRON: Reminders sent. Upcoming: ${upcomingDue.length}, Overdue: ${overdue.length}`);
    } catch (err) {
      logger.error('CRON: Payment reminder failed:', err);
    }
  }, { timezone: 'Asia/Kolkata' });

  // ─── 15th of month: Late fee application ────────────────────────────────────
  cron.schedule('0 11 15 * *', async () => {
    logger.info('CRON: Applying late fees...');
    try {
      const month = new Date().getMonth() + 1;
      const year = new Date().getFullYear();

      const overdueTransactions = await LedgerTransaction.find({
        month, year,
        category: 'maintenance',
        status: 'overdue',
        lateFeeApplied: false,
      }).populate('member');

      for (const txn of overdueTransactions) {
        if (!txn.member) continue;
        const lateFeeAmount = (txn.amount * txn.member.lateFeePercentage) / 100;
        const balance = await LedgerTransaction.getRunningBalance(txn.member._id);

        await LedgerTransaction.create({
          member: txn.member._id,
          type: 'debit',
          category: 'late_fee',
          amount: lateFeeAmount,
          description: `Late fee for ${txn.description}`,
          date: new Date(), month, year,
          balance: balance + lateFeeAmount,
          status: 'pending',
          isAutoGenerated: true,
        });

        txn.lateFeeApplied = true;
        await txn.save();
      }

      logger.info(`CRON: Late fees applied to ${overdueTransactions.length} transactions`);
    } catch (err) {
      logger.error('CRON: Late fee application failed:', err);
    }
  }, { timezone: 'Asia/Kolkata' });

  logger.info('✅ Cron jobs started successfully');
};
